alice:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Trajectory Controllers -------------------------------------
  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
    gains:
      base_joint:
        p: 1.8
        i: 0.01
        d: 0.05
      shoulder_joint:
        p: 5.0
        i: 1.0
        d: 0.2
      elbow_joint:
        p: 2.8
        i: 0.0
        d: 0.0
      wrist_pitch_joint:
        p: 2.0
        i: 0.0
        d: 0.0
        
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.02
      base_joint:
        trajectory: 0.05
        goal: 0.02
      shoulder_joint:
        trajectory: 0.05
        goal: 0.02
      elbow_joint:
        trajectory: 0.05
        goal: 0.02
      wrist_pitch_joint:
        trajectory: 0.05
        goal: 0.02