alice:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_joint_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 1.8, i: 0.0, d: 0.05}

  shoulder_joint_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 5.0, i: 1.0, d: 0.2}

  elbow_joint_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 2.8, i: 0.0, d: 0.0}

  wrist_pitch_joint_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}