(cl:defpackage alice_octomap-srv
  (:use )
  (:export
   "OCTOMAP_SRV_CLIENT"
   "<OCTOMAP_SRV_CLIENT-REQUEST>"
   "OCTOMAP_SRV_CLIENT-REQUEST"
   "<OCTOMAP_SRV_CLIENT-RESPONSE>"
   "OCTOMAP_SRV_CLIENT-RESPONSE"
  ))

