controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_camera_ee_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: arm
    pose: Home