controller_list:
  - name: alice/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint

trajectory_execution:
  allowed_execution_duration_scaling: 1.4
  allowed_goal_duration_margin: 0.8
  allowed_start_tolerance: 0.02