arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - wrist_pitch_joint
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1