controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint