// Generated by gencpp from file alice_octomap/octomap_srv_client.msg
// DO NOT EDIT!


#ifndef ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENT_H
#define ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENT_H

#include <ros/service_traits.h>


#include <alice_octomap/octomap_srv_clientRequest.h>
#include <alice_octomap/octomap_srv_clientResponse.h>


namespace alice_octomap
{

struct octomap_srv_client
{

typedef octomap_srv_clientRequest Request;
typedef octomap_srv_clientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct octomap_srv_client
} // namespace alice_octomap


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_octomap::octomap_srv_client > {
  static const char* value()
  {
    return "c2ce102c71339eb15c8ed24c4bfa8169";
  }

  static const char* value(const ::alice_octomap::octomap_srv_client&) { return value(); }
};

template<>
struct DataType< ::alice_octomap::octomap_srv_client > {
  static const char* value()
  {
    return "alice_octomap/octomap_srv_client";
  }

  static const char* value(const ::alice_octomap::octomap_srv_client&) { return value(); }
};


// service_traits::MD5Sum< ::alice_octomap::octomap_srv_clientRequest> should match
// service_traits::MD5Sum< ::alice_octomap::octomap_srv_client >
template<>
struct MD5Sum< ::alice_octomap::octomap_srv_clientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_octomap::octomap_srv_client >::value();
  }
  static const char* value(const ::alice_octomap::octomap_srv_clientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_octomap::octomap_srv_clientRequest> should match
// service_traits::DataType< ::alice_octomap::octomap_srv_client >
template<>
struct DataType< ::alice_octomap::octomap_srv_clientRequest>
{
  static const char* value()
  {
    return DataType< ::alice_octomap::octomap_srv_client >::value();
  }
  static const char* value(const ::alice_octomap::octomap_srv_clientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_octomap::octomap_srv_clientResponse> should match
// service_traits::MD5Sum< ::alice_octomap::octomap_srv_client >
template<>
struct MD5Sum< ::alice_octomap::octomap_srv_clientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_octomap::octomap_srv_client >::value();
  }
  static const char* value(const ::alice_octomap::octomap_srv_clientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_octomap::octomap_srv_clientResponse> should match
// service_traits::DataType< ::alice_octomap::octomap_srv_client >
template<>
struct DataType< ::alice_octomap::octomap_srv_clientResponse>
{
  static const char* value()
  {
    return DataType< ::alice_octomap::octomap_srv_client >::value();
  }
  static const char* value(const ::alice_octomap::octomap_srv_clientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENT_H
