// Generated by gencpp from file alice_octomap/octomap.msg
// DO NOT EDIT!


#ifndef ALICE_OCTOMAP_MESSAGE_OCTOMAP_H
#define ALICE_OCTOMAP_MESSAGE_OCTOMAP_H

#include <ros/service_traits.h>


#include <alice_octomap/octomapRequest.h>
#include <alice_octomap/octomapResponse.h>


namespace alice_octomap
{

struct octomap
{

typedef octomapRequest Request;
typedef octomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct octomap
} // namespace alice_octomap


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alice_octomap::octomap > {
  static const char* value()
  {
    return "e49c62c1add6ce5ed13e188a48e66fc4";
  }

  static const char* value(const ::alice_octomap::octomap&) { return value(); }
};

template<>
struct DataType< ::alice_octomap::octomap > {
  static const char* value()
  {
    return "alice_octomap/octomap";
  }

  static const char* value(const ::alice_octomap::octomap&) { return value(); }
};


// service_traits::MD5Sum< ::alice_octomap::octomapRequest> should match
// service_traits::MD5Sum< ::alice_octomap::octomap >
template<>
struct MD5Sum< ::alice_octomap::octomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alice_octomap::octomap >::value();
  }
  static const char* value(const ::alice_octomap::octomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_octomap::octomapRequest> should match
// service_traits::DataType< ::alice_octomap::octomap >
template<>
struct DataType< ::alice_octomap::octomapRequest>
{
  static const char* value()
  {
    return DataType< ::alice_octomap::octomap >::value();
  }
  static const char* value(const ::alice_octomap::octomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alice_octomap::octomapResponse> should match
// service_traits::MD5Sum< ::alice_octomap::octomap >
template<>
struct MD5Sum< ::alice_octomap::octomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alice_octomap::octomap >::value();
  }
  static const char* value(const ::alice_octomap::octomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alice_octomap::octomapResponse> should match
// service_traits::DataType< ::alice_octomap::octomap >
template<>
struct DataType< ::alice_octomap::octomapResponse>
{
  static const char* value()
  {
    return DataType< ::alice_octomap::octomap >::value();
  }
  static const char* value(const ::alice_octomap::octomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICE_OCTOMAP_MESSAGE_OCTOMAP_H
