// Generated by gencpp from file alice_octomap/octomap_srv_clientResponse.msg
// DO NOT EDIT!


#ifndef ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENTRESPONSE_H
#define ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alice_octomap
{
template <class ContainerAllocator>
struct octomap_srv_clientResponse_
{
  typedef octomap_srv_clientResponse_<ContainerAllocator> Type;

  octomap_srv_clientResponse_()
    : occupied_voxels(0)  {
    }
  octomap_srv_clientResponse_(const ContainerAllocator& _alloc)
    : occupied_voxels(0)  {
  (void)_alloc;
    }



   typedef int32_t _occupied_voxels_type;
  _occupied_voxels_type occupied_voxels;





  typedef boost::shared_ptr< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> const> ConstPtr;

}; // struct octomap_srv_clientResponse_

typedef ::alice_octomap::octomap_srv_clientResponse_<std::allocator<void> > octomap_srv_clientResponse;

typedef boost::shared_ptr< ::alice_octomap::octomap_srv_clientResponse > octomap_srv_clientResponsePtr;
typedef boost::shared_ptr< ::alice_octomap::octomap_srv_clientResponse const> octomap_srv_clientResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator1> & lhs, const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator2> & rhs)
{
  return lhs.occupied_voxels == rhs.occupied_voxels;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator1> & lhs, const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alice_octomap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2ce102c71339eb15c8ed24c4bfa8169";
  }

  static const char* value(const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2ce102c71339eb1ULL;
  static const uint64_t static_value2 = 0x5c8ed24c4bfa8169ULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_octomap/octomap_srv_clientResponse";
  }

  static const char* value(const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 occupied_voxels\n"
;
  }

  static const char* value(const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.occupied_voxels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct octomap_srv_clientResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_octomap::octomap_srv_clientResponse_<ContainerAllocator>& v)
  {
    s << indent << "occupied_voxels: ";
    Printer<int32_t>::stream(s, indent + "  ", v.occupied_voxels);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_OCTOMAP_MESSAGE_OCTOMAP_SRV_CLIENTRESPONSE_H
