// Generated by gencpp from file alice_octomap/octomapResponse.msg
// DO NOT EDIT!


#ifndef ALICE_OCTOMAP_MESSAGE_OCTOMAPRESPONSE_H
#define ALICE_OCTOMAP_MESSAGE_OCTOMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alice_octomap
{
template <class ContainerAllocator>
struct octomapResponse_
{
  typedef octomapResponse_<ContainerAllocator> Type;

  octomapResponse_()
    : occupied_voxels(0)
    , total_voxels(0)  {
    }
  octomapResponse_(const ContainerAllocator& _alloc)
    : occupied_voxels(0)
    , total_voxels(0)  {
  (void)_alloc;
    }



   typedef int32_t _occupied_voxels_type;
  _occupied_voxels_type occupied_voxels;

   typedef int32_t _total_voxels_type;
  _total_voxels_type total_voxels;





  typedef boost::shared_ptr< ::alice_octomap::octomapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alice_octomap::octomapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct octomapResponse_

typedef ::alice_octomap::octomapResponse_<std::allocator<void> > octomapResponse;

typedef boost::shared_ptr< ::alice_octomap::octomapResponse > octomapResponsePtr;
typedef boost::shared_ptr< ::alice_octomap::octomapResponse const> octomapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alice_octomap::octomapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alice_octomap::octomapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alice_octomap::octomapResponse_<ContainerAllocator1> & lhs, const ::alice_octomap::octomapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.occupied_voxels == rhs.occupied_voxels &&
    lhs.total_voxels == rhs.total_voxels;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alice_octomap::octomapResponse_<ContainerAllocator1> & lhs, const ::alice_octomap::octomapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alice_octomap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alice_octomap::octomapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alice_octomap::octomapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_octomap::octomapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alice_octomap::octomapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_octomap::octomapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alice_octomap::octomapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alice_octomap::octomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6c656edb646bcaf655c3aa23e2812b3";
  }

  static const char* value(const ::alice_octomap::octomapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6c656edb646bcafULL;
  static const uint64_t static_value2 = 0x655c3aa23e2812b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::alice_octomap::octomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alice_octomap/octomapResponse";
  }

  static const char* value(const ::alice_octomap::octomapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alice_octomap::octomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 occupied_voxels\n"
"int32 total_voxels\n"
;
  }

  static const char* value(const ::alice_octomap::octomapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alice_octomap::octomapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.occupied_voxels);
      stream.next(m.total_voxels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct octomapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alice_octomap::octomapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alice_octomap::octomapResponse_<ContainerAllocator>& v)
  {
    s << indent << "occupied_voxels: ";
    Printer<int32_t>::stream(s, indent + "  ", v.occupied_voxels);
    s << indent << "total_voxels: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_voxels);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICE_OCTOMAP_MESSAGE_OCTOMAPRESPONSE_H
